Repository nautechsystems/nautilus_trader, pull requests merged in 2025-07, with the labels that each got.

#2750 Add trailing stop orders activation_price support for Rust
  crates/execution/src/matching_core/mod.rs
  crates/execution/src/matching_engine/engine.rs
  crates/execution/src/order_emulator/emulator.rs
  crates/execution/src/trailing.rs
  crates/model/src/orders/any.rs
  crates/model/src/orders/mod.rs
  crates/model/src/orders/trailing_stop_limit.rs
  crates/model/src/orders/trailing_stop_market.rs
Labels: rust

#2758 Fix dYdX Take Profit order type mapping error
  nautilus_trader/adapters/dydx/common/enums.py
  tests/integration_tests/adapters/dydx/test_parsing.py
Labels: python

#2796 Improve DEX pool sync process in the blockchain adapter
  crates/adapters/blockchain/bin/node_test.rs
  crates/adapters/blockchain/src/cache/database.rs
  crates/adapters/blockchain/src/cache/mod.rs
  crates/adapters/blockchain/src/cache/rows.rs
  crates/adapters/blockchain/src/contracts/base.rs
  crates/adapters/blockchain/src/contracts/erc20.rs
  crates/adapters/blockchain/src/contracts/mod.rs
  crates/adapters/blockchain/src/data.rs
  crates/adapters/blockchain/src/reporting.rs
  crates/adapters/blockchain/src/rpc/http.rs
  crates/common/src/actor/tests.rs
  crates/common/src/cache/tests.rs
  crates/common/src/python/actor.rs
  crates/data/tests/engine.rs
  crates/model/src/defi/amm.rs
  crates/model/src/python/defi/types.rs
Labels: rust

#2789 OKX: Complete bar request implementation
  Cargo.lock
  crates/adapters/okx/Cargo.toml
  crates/adapters/okx/src/common/testing.rs
  crates/adapters/okx/src/http/client.rs
  nautilus_trader/adapters/okx/data.py
Labels: adapter
