Repository nautechsystems/nautilus_trader, pull requests merged in 2025-04, with the labels that each got.

#2489 Fix colored logging
  crates/common/src/enums.rs
  crates/common/src/logging/logger.rs
Labels: bug

#2524 Improve consistency of environment variables for build
  Makefile
  build.py
Labels: build/tooling

#2535 Implement Block primitive for blockchain domain model
  Makefile
  crates/model/src/defi/block.rs
  crates/model/src/defi/mod.rs
  crates/model/src/defi/rpc.rs
Labels: rust

#2539 Improve build time by only compiling libraries
  build.py
Labels: build/tooling

#2551 Implement Transaction primitive for blockchain domain model
  crates/model/src/defi/block.rs
  crates/model/src/defi/hex.rs
  crates/model/src/defi/mod.rs
  crates/model/src/defi/rpc.rs
  crates/model/src/defi/transaction.rs
Labels: rust
